### ISSUE TITLE
Low mAP when training on aerial images

### ISSUE THREAD

**Issue by DINHQuangDung1999** [explainingai-code/FasterRCNN-PyTorch#2]
Hi, 

First of all, thank you for providing this code library which is very helpful for me to learn Faster RCNN. 
I have tried your code on a custom split of PascalVOC, and the result was okay in my opinion. I did two experiment with VGG16 backbone trained for 40 epochs and ResNet101 trained for 10 epochs. 

![image](https://github.com/user-attachments/assets/dc70d384-c915-4cf0-a310-118bc0a8e335)

However, when I try with aerial images like DOTA, the mAP is quite low, at around 35 mAP@0.5 after 10 epochs of training. Here, I use ResNet101 as the backbone. Moreover, I found that the model usually output a lot of meaningless boxes beside correct boxes (high False Positive Rate), as in the following images.

![image](https://github.com/user-attachments/assets/bd70e7e3-0212-4bfe-866d-0fe0aedf75a0)
![image](https://github.com/user-attachments/assets/23f4d19a-c351-4e73-b6ad-1fd2c52f88d5)
![image](https://github.com/user-attachments/assets/78a5544a-7f00-4d77-8b36-2e9c13c9a1e3)

I wonder if you have ever experience this situation. Thank you in advance.

**Comment by explainingai-code** [comment]
Hello @DINHQuangDung1999 , Thank you for your appreciation.
I have never worked with DOTA dataset so am not sure what the exact issue might be.
From the paper(https://arxiv.org/pdf/1711.10398) I see that with HBB ground truths, Faster RCNN gets around 60.46, so the 35% mAP that we are getting seems very less.
I assume you are using the same training/evaluation mechanism as the paper(5.2). I do see you have a dataloader which seems to be doing all of that but just wanted to confirm.

Ideally if we are doing all that and also using the same configuration parameters(like aspect ratios of  0.3/0.5/1/2/4, number of proposals e.t.c) from https://github.com/jessemelpolio/Faster_RCNN_for_DOTA/blob/499b32c3893ccd8850e0aca07e5afb952d08943e/experiments/faster_rcnn/cfgs/DOTA.yaml then we should get the same result or atleast close.

**Comment by DINHQuangDung1999** [comment]
Hi @explainingai-code , thank you for replying! 

It seems weird that when I use VGG16 backbone I get better mAP, at 40mAP after the first epoch and 48mAP after 3 epochs. I think I need to do more experiments.

**Comment by DINHQuangDung1999** [comment]
Hi @explainingai-code, 

Can you explain why you set the low_score_threshold to 0.7 in the inference code at ![this line](https://github.com/explainingai-code/FasterRCNN-PyTorch/blob/3205c88cd2748eff0d669be87af8fedb09d38c05/tools/infer.py#L192C5-L192C57?) Is it normal to expect correctly labeled objects having score >0.7 and ideally close to 1?

**Comment by explainingai-code** [comment]
@DINHQuangDung1999 , there are two different values for low score threshold. One for visualizing detections and other for mAP evaluation.
The infer method is just to visualize few sample detections and similar to [this method](https://github.com/rbgirshick/py-faster-rcnn/blob/781a917b378dbfdedb45b6a56189a31982da1b43/tools/demo.py#L72) of py-faster-rcnn repo , which uses a higher confidence threshold. The paper also in Figure 5, shows visualisations with 0.6 score threshold, so based on few sample images I found 0.7 worked fine so used that only for the infer part.

But the score threshold for mAP computation is still a very low one(0.05), same value is used in the [pytorch faster rcnn codebase](https://github.com/pytorch/vision/blob/main/torchvision/models/detection/faster_rcnn.py#L193) as well as for mAP evaluation in [py-faster-rcnn test method ](https://github.com/rbgirshick/py-faster-rcnn/blob/781a917b378dbfdedb45b6a56189a31982da1b43/lib/fast_rcnn/test.py#L227) , which is what I use in the [evaluate_map](https://github.com/explainingai-code/FasterRCNN-PyTorch/blob/3205c88cd2748eff0d669be87af8fedb09d38c05/tools/infer.py#L263) method in this repo. And is the default value provided in config (https://github.com/explainingai-code/FasterRCNN-PyTorch/blob/3205c88cd2748eff0d669be87af8fedb09d38c05/config/voc.yaml#L30)

**Comment by explainingai-code** [comment]
Just looked at the DOTA repo and found that they use a much lower threshold for visualizing. https://github.com/jessemelpolio/Faster_RCNN_for_DOTA/blob/499b32c3893ccd8850e0aca07e5afb952d08943e/faster_rcnn/core/tester.py#L777
